version: "3.9"

services:
  mongo_auth:
    container_name: mongo_auth
    image: mongo:latest
    restart: always
    networks:
      - my-network
    volumes:
      - mongo_auth-data:/data/db

  auth_service:
    build: ./services/auth
    container_name: auth_service
    ports:
      - 5010:5010
    environment:
      PORT: 5010
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: EduSpace_auth
    depends_on: 
      - mongo_auth
  
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - '5000:5000'
    networks:
      - my-network
    depends_on:
      - auth_service
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  mongo_auth-data:

 