
version: "3.9"

services:
  mongo_auth:
    container_name: mongo_auth
    image: mongo:latest
    restart: always
    networks:
      - my-network
    volumes:
      - mongo_auth-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - my-network
    restart: always
    
  auth_service:
    build: ./services/auth
    container_name: auth_service
    ports:
      - 5010:5010
    environment:
      PORT: 5010
      MONGODB_URI: mongodb://mongo_auth:27017
      DB_NAME: EduSpace_auth
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on: 
      - mongo_auth
      - redis
    networks:
      - my-network
    volumes:
      - ./services/auth:/usr/src/app  
      - /usr/src/app/node_modules
    

  api-gateway:
    build: ./apiGateway
    container_name: api_gateway
    ports:
      - '5000:5000'
    environment:
      AUTH_SERVICE_URL: http://auth_service:5010
      USER_SERVICE_URL: http://localhost:5020
    networks:
      - my-network
    depends_on:
      - auth_service
      - mongo_auth
    restart: always
    volumes:
      - ./apiGateway:/usr/src/app  
      - /usr/src/app/node_modules

networks:
  my-network:
    driver: bridge

volumes:
  mongo_auth-data:
