version: "3.9"

services:
  mysql:
    container_name: auth_db_container
    image: mysql:latest
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
    volumes:
      - mysql:/var/lib/mysql

  api:
    build: .
    ports:
      - 5010:5010
    environment:
      PORT: 5010
      NODE_ENV: "development"
    depends_on:
      - mysql

volumes:
  mysql: {}
